# Risk Management & Cybersecurity Category
# Based on research of actual earnings call language from US and Canadian banks
# Critical for operational resilience and regulatory compliance

- name: "Risk Management & Cybersecurity"
  
  description: |
    Discussion of enterprise risk management, operational risk, market risk, cyber threats,
    data security, fraud prevention, and risk frameworks. Includes risk appetite, stress
    testing scenarios, control environments, and security investments. Critical for
    maintaining trust and meeting regulatory expectations.
  
  detailed_scope:
    includes:
      # Enterprise Risk Management
      - Risk appetite framework
      - Risk governance
      - Enterprise risk management (ERM)
      - Risk culture
      - Three lines of defense
      - Risk committees
      - Chief Risk Officer updates
      
      # Operational Risk
      - Operational risk losses
      - Control environment
      - Process risks
      - System failures
      - Business continuity
      - Disaster recovery
      - Vendor/third-party risk
      
      # Market Risk
      - Trading risk metrics (VaR)
      - Interest rate risk
      - Foreign exchange risk
      - Commodity risk
      - Counterparty risk
      - Model risk management
      
      # Cybersecurity
      - Cyber threats/attacks
      - Data breaches
      - Security investments
      - Cyber resilience
      - Information security
      - Identity and access management
      - Zero trust architecture
      
      # Fraud & Financial Crime
      - Fraud losses/prevention
      - Anti-money laundering (AML)
      - Know Your Customer (KYC)
      - Sanctions compliance
      - Financial crime prevention
      
      # Risk Metrics & Testing
      - Risk-weighted assets (context)
      - Stress testing (operational)
      - Scenario analysis
      - Key risk indicators (KRIs)
      - Risk limits and breaches
      
    excludes:
      - Credit risk details (separate category)
      - Capital ratios (Capital Management)
      - Insurance products
      - Investment risk for clients
  
  key_indicators:
    # Primary indicators - strongest signals
    primary:
      - "risk management"
      - "operational risk"
      - "cyber"
      - "cybersecurity"
      - "cyber security"
      - "data breach"
      - "fraud"
      - "fraud losses"
      - "security"
      - "information security"
      - "cyber attack"
      - "cyber threat"
      - "market risk"
      - "VaR"
      - "value at risk"
      - "risk framework"
      - "risk appetite"
      - "control environment"
      - "AML"
      - "anti-money laundering"
      - "financial crime"
      
    # Secondary indicators
    secondary:
      - "enterprise risk"
      - "ERM"
      - "operational losses"
      - "control failures"
      - "risk governance"
      - "risk culture"
      - "three lines of defense"
      - "first line"
      - "second line"
      - "risk function"
      - "model risk"
      - "model validation"
      - "counterparty risk"
      - "concentration risk"
      - "liquidity risk" # (market context)
      - "interest rate risk"
      - "IRRBB" # Interest Rate Risk in Banking Book
      - "duration risk"
      - "basis risk"
      - "FX risk"
      - "foreign exchange risk"
      - "commodity risk"
      - "ransomware"
      - "phishing"
      - "malware"
      - "DDoS" # Distributed Denial of Service
      - "penetration testing"
      - "vulnerability"
      - "patch management"
      - "encryption"
      - "data privacy"
      - "GDPR"
      - "CCPA"
      - "privacy"
      - "data protection"
      - "identity theft"
      - "account takeover"
      - "synthetic fraud"
      - "KYC"
      - "know your customer"
      - "CDD" # Customer Due Diligence
      - "EDD" # Enhanced Due Diligence
      - "sanctions"
      - "OFAC"
      - "BSA" # Bank Secrecy Act
      - "suspicious activity"
      - "SAR" # Suspicious Activity Report
      - "business continuity"
      - "BCP" # Business Continuity Planning
      - "disaster recovery"
      - "resilience"
      - "operational resilience"
      - "third-party risk"
      - "vendor risk"
      - "supply chain risk"
      - "outsourcing risk"
      - "conduct risk"
      - "reputational risk"
      
    # Contextual indicators
    contextual:
      - "threat" # (security threat)
      - "vulnerability"
      - "exposure" # (risk exposure)
      - "incident" # (security incident)
      - "breach"
      - "attack"
      - "compromise"
      - "unauthorized"
      - "mitigation"
      - "remediation"
      - "controls"
      - "safeguards"
      - "monitoring"
      - "detection"
      - "prevention"
      - "response"
      - "recovery"
  
  common_phrases:
    positive_signals:
      # Strong Risk Management
      - "robust risk management"
      - "strong control environment"
      - "risk within appetite"
      - "no material breaches"
      - "enhanced risk framework"
      - "improved risk metrics"
      
      # Cybersecurity Strength
      - "no significant cyber incidents"
      - "cyber defenses held"
      - "security investments paying off"
      - "prevented X attacks"
      - "cyber resilience improved"
      
      # Fraud Prevention
      - "fraud losses declining"
      - "fraud prevention effective"
      - "improved detection rates"
      - "reduced financial crime"
      
    negative_signals:
      - "cyber incident disclosed"
      - "data breach occurred"
      - "operational losses elevated"
      - "control failures identified"
      - "risk limit breaches"
      - "fraud losses increasing"
      - "regulatory findings on risk"
      - "heightened cyber threats"
      - "ransomware attack"
      - "vendor compromise"
  
  quantitative_patterns:
    # Risk metrics
    - "VaR of $X million"
    - "operational losses of $X million"
    - "X% of risk limit"
    - "X risk events"
    
    # Cyber metrics
    - "X cyber attacks prevented"
    - "X% reduction in incidents"
    - "$X million cyber investment"
    - "X security professionals hired"
    
    # Fraud metrics
    - "fraud losses of $X million"
    - "X basis points fraud rate"
    - "X% fraud detection rate"
    - "$X million in prevented fraud"
  
  bank_specific_terminology:
    # US Banks
    JPMorgan:
      metrics: ["Operational risk capital", "Firm-wide VaR"]
      focus: ["Fortress balance sheet", "Cyber defense investment"]
      spending: "$15B+ on technology and risk"
      
    Bank_of_America:
      framework: ["Responsible growth risk framework"]
      metrics: ["Risk appetite metrics", "Operational loss rates"]
      focus: "Enterprise-wide risk management"
      
    Wells_Fargo:
      priorities: ["Risk and control remediation", "Operational excellence"]
      programs: ["Control enhancements", "Risk infrastructure rebuild"]
      
    Citigroup:
      initiatives: ["Transformation includes risk", "Control environment upgrade"]
      focus: "Consent order remediation"
      
    Goldman_Sachs:
      metrics: ["95% VaR", "Risk factor sensitivities"]
      focus: "Market risk management excellence"
      
    Morgan_Stanley:
      framework: ["Integrated risk management"]
      focus: "Operational resilience"
    
    # Canadian Banks
    Royal_Bank_RY:
      framework: ["Enterprise risk management framework"]
      governance: ["Risk committee oversight", "Three lines of defense"]
      focus: "Cyber security leadership"
      
    TD_Bank:
      programs: ["Operational risk management", "Enhanced controls"]
      metrics: ["Risk appetite statement", "Key risk indicators"]
      regulatory: "AML program enhancements"
      
    Bank_of_Montreal_BMO:
      approach: ["Risk culture", "Proactive risk management"]
      focus: "Operational resilience"
      
    Scotiabank_BNS:
      framework: ["Global risk management"]
      geographic: "Country risk management"
      
    CIBC_CM:
      priorities: ["Risk discipline", "Control effectiveness"]
      metrics: "Risk-adjusted returns"
      
    National_Bank_NA:
      approach: ["Prudent risk management"]
      focus: "Proportional to size"
  
  canadian_specific_patterns:
    regulatory_focus:
      - OSFI operational resilience
      - Privacy laws (PIPEDA)
      - AML/ATF requirements
      - Cyber security guidelines
      
    terminology:
      - "Operational risk management"
      - "Enterprise-wide risk"
      - "Risk appetite framework"
      - "Control effectiveness"
      
    reporting:
      - Risk committee updates
      - Quarterly risk metrics
      - Integrated risk reporting
      - Board risk oversight
  
  cyber_threat_landscape:
    threat_types:
      - "nation-state actors"
      - "organized crime"
      - "hacktivists"
      - "insider threats"
      - "supply chain attacks"
      
    attack_vectors:
      - "ransomware"
      - "phishing/social engineering"
      - "zero-day exploits"
      - "API attacks"
      - "cloud vulnerabilities"
      - "IoT exploits"
      
    defense_strategies:
      - "zero trust architecture"
      - "defense in depth"
      - "threat intelligence"
      - "security operations center (SOC)"
      - "incident response team"
      - "red team/blue team"
  
  operational_risk_categories:
    internal:
      - "process failures"
      - "system failures"
      - "human errors"
      - "internal fraud"
      
    external:
      - "external fraud"
      - "natural disasters"
      - "vendor failures"
      - "cyber attacks"
      
    regulatory:
      - "compliance failures"
      - "reporting errors"
      - "conduct issues"
  
  market_risk_language:
    metrics:
      - "value at risk (VaR)"
      - "stressed VaR"
      - "expected shortfall"
      - "risk sensitivities"
      - "Greeks" # Options risk
      
    exposures:
      - "interest rate exposure"
      - "credit spread risk"
      - "equity risk"
      - "commodity risk"
      - "FX risk"
      
    management:
      - "hedging strategies"
      - "risk limits"
      - "stress testing"
      - "scenario analysis"
  
  fraud_prevention_language:
    types:
      - "card fraud"
      - "check fraud"
      - "wire fraud"
      - "account takeover"
      - "identity theft"
      - "synthetic identity"
      - "first-party fraud"
      
    controls:
      - "fraud detection models"
      - "transaction monitoring"
      - "behavioral analytics"
      - "biometric authentication"
      - "multi-factor authentication"
      - "fraud scoring"
  
  classification_examples:
    
    should_classify:
      - text: "We successfully defended against 10 million cyber attacks this quarter"
        reason: "Cybersecurity metrics"
        
      - text: "Operational risk losses remained low at $50 million"
        reason: "Operational risk metric"
        
      - text: "Enhanced our AML controls and transaction monitoring"
        reason: "Financial crime prevention"
        
      - text: "VaR averaged $35 million in the trading book"
        reason: "Market risk metric"
        
      - text: "Fraud losses declined 20% due to new detection models"
        reason: "Fraud prevention results"
        
      - text: "Investing $500 million in cyber defenses"
        reason: "Cybersecurity investment"
        
      - text: "No material risk appetite breaches this quarter"
        reason: "Risk management framework"
    
    should_not_classify:
      - text: "Credit losses normalized"
        reason: "Credit Quality category"
        
      - text: "Technology spending increased"
        reason: "Technology or Expenses category"
        
      - text: "Regulatory capital ratios strong"
        reason: "Capital Management category"
        
      - text: "Compliance costs were elevated"
        reason: "Regulatory category for costs"
  
  co_occurrence_patterns:
    frequently_with:
      - "Regulatory & Compliance" # Risk and compliance linked
      - "Technology & Digital" # Cyber is tech risk
      - "Operational Expenses" # Risk management costs
      
    sometimes_with:
      - "Credit Quality" # Overall risk picture
      - "Strategic Initiatives" # Risk transformation
      
    rarely_with:
      - "Revenue Growth" # Different focus
      - "Net Interest Income" # Different domain
  
  control_environment_language:
    governance:
      - "board oversight"
      - "risk committee"
      - "audit committee"
      - "management oversight"
      
    framework:
      - "COSO framework"
      - "control self-assessment"
      - "risk and control matrix"
      - "control testing"
      - "control effectiveness"
      
    improvement:
      - "control enhancements"
      - "remediation efforts"
      - "control gaps closed"
      - "process improvements"
  
  red_flags_for_misclassification:
    - "Credit risk details go to Credit Quality category"
    - "Capital and liquidity risk go to Capital Management"
    - "Regulatory compliance COSTS go to Regulatory category"
    - "Technology infrastructure (non-security) is Technology category"
    - "Insurance products are business line discussions"
    - "Client investment risk is Wealth Management"
    - "Reputation by itself needs other context"

  prompt_guidance_for_llm: |
    When classifying content as Risk Management & Cybersecurity:
    
    CORE IDENTIFICATION:
    1. Look for RISK MANAGEMENT and SECURITY discussions
    2. Key themes: Operational risk, cyber, fraud, market risk
    3. Control environment and governance
    4. Security incidents and prevention
    5. Risk metrics and frameworks
    
    KEY COMPONENTS:
    6. Enterprise Risk: Governance, appetite, culture
    7. Operational Risk: Losses, controls, failures
    8. Cybersecurity: Threats, defenses, incidents
    9. Market Risk: VaR, sensitivities, exposures
    10. Fraud/Crime: Prevention, losses, AML/KYC
    
    RISK TYPES INCLUDED:
    - Operational (process, people, systems)
    - Market (trading, rates, FX)
    - Cyber (attacks, breaches, defense)
    - Fraud (losses, prevention)
    - Model (validation, governance)
    - Third-party (vendor, outsourcing)
    - Conduct (behavior, ethics)
    
    CYBERSECURITY FOCUS:
    - Threat landscape
    - Attack prevention
    - Incident response
    - Security investments
    - Data protection
    - Identity management
    - Zero trust architecture
    
    FRAUD & FINANCIAL CRIME:
    - Fraud types and losses
    - Detection and prevention
    - AML/KYC programs
    - Sanctions compliance
    - Suspicious activity
    - Transaction monitoring
    
    RISK METRICS:
    - VaR (Value at Risk)
    - Operational losses
    - Fraud rates
    - Incident counts
    - Control effectiveness
    - Risk appetite metrics
    
    GEOGRAPHIC DIFFERENCES:
    US BANKS:
    - Fed/OCC risk expectations
    - BSA/AML requirements
    - State privacy laws
    - Consent orders (some banks)
    
    CANADIAN BANKS:
    - OSFI risk guidelines
    - PIPEDA privacy
    - FINTRAC AML
    - Operational resilience focus
    
    GOVERNANCE & CONTROL:
    - Three lines of defense
    - Risk committees
    - Control testing
    - Risk appetite framework
    - Stress testing (operational)
    
    EXCLUSIONS:
    - Credit risk specifics
    - Capital/liquidity ratios
    - Regulatory compliance costs
    - Technology (non-security)
    - Insurance products
    - Client investment risk
    
    REMEMBER:
    - This is about MANAGING RISK
    - Includes both prevention and response
    - Cyber is increasingly important
    - Controls and governance central
    - Multiple risk types together