# Macro & Market Environment Category
# Based on research of actual earnings call language from US and Canadian banks
# External factors affecting bank performance and strategy

- name: "Macro & Market Environment"
  
  description: |
    Discussion of economic conditions, interest rate environment, inflation, GDP growth,
    unemployment, market volatility, geopolitical events, and industry trends. Includes
    Federal Reserve/central bank policy, economic outlook, market conditions, and competitive
    landscape. Critical context for understanding performance drivers and outlook.
  
  detailed_scope:
    includes:
      # Economic Conditions
      - GDP growth/recession
      - Inflation/deflation
      - Unemployment rates
      - Consumer confidence
      - Business confidence
      - Economic cycles
      - Economic forecasts
      - Recession probability
      
      # Monetary Policy
      - Federal Reserve policy
      - Interest rate decisions
      - Quantitative easing/tightening
      - Central bank actions
      - FOMC meetings
      - Dot plot projections
      - Bank of Canada policy
      
      # Market Conditions
      - Market volatility
      - Equity markets
      - Credit markets
      - Bond yields
      - Yield curve shape
      - Credit spreads
      - Market liquidity
      - IPO/M&A markets
      
      # Industry Dynamics
      - Competitive environment
      - Industry consolidation
      - Market share dynamics
      - Pricing pressure
      - Industry trends
      - Disruption threats
      - Regulatory landscape
      
      # Geopolitical
      - Geopolitical tensions
      - Trade wars/tariffs
      - Brexit impacts
      - Sanctions impacts
      - Political uncertainty
      - Elections impact
      - Global events
      
      # Other Factors
      - Housing market
      - Energy prices
      - Currency movements
      - Commodity prices
      - Supply chain issues
      - Labor market conditions
      
    excludes:
      - Bank-specific strategies
      - Internal performance metrics
      - Specific product discussions
      - Company guidance
  
  key_indicators:
    # Primary indicators - strongest signals
    primary:
      - "macro"
      - "macroeconomic"
      - "economy"
      - "economic"
      - "GDP"
      - "inflation"
      - "unemployment"
      - "recession"
      - "interest rates"
      - "Fed"
      - "Federal Reserve"
      - "FOMC"
      - "central bank"
      - "Bank of Canada" # Canadian
      - "monetary policy"
      - "market conditions"
      - "market environment"
      - "market volatility"
      - "yield curve"
      - "geopolitical"
      - "industry"
      - "competitive"
      
    # Secondary indicators
    secondary:
      - "economic growth"
      - "economic outlook"
      - "economic cycle"
      - "business cycle"
      - "soft landing"
      - "hard landing"
      - "stagflation"
      - "deflation"
      - "hyperinflation"
      - "CPI" # Consumer Price Index
      - "PCE" # Personal Consumption Expenditures
      - "labor market"
      - "job growth"
      - "wage growth"
      - "rate hike"
      - "rate cut"
      - "rate pause"
      - "dovish"
      - "hawkish"
      - "neutral rate"
      - "terminal rate"
      - "QE" # Quantitative Easing
      - "QT" # Quantitative Tightening
      - "taper"
      - "balance sheet runoff"
      - "equity markets"
      - "S&P 500"
      - "Dow"
      - "NASDAQ"
      - "TSX" # Canadian
      - "bear market"
      - "bull market"
      - "correction"
      - "volatility index"
      - "VIX"
      - "credit spreads"
      - "investment grade spreads"
      - "high yield spreads"
      - "treasury yields"
      - "10-year yield"
      - "2-year yield"
      - "inverted yield curve"
      - "steepening"
      - "flattening"
      - "housing market"
      - "home prices"
      - "mortgage rates"
      - "oil prices"
      - "commodity prices"
      - "dollar strength"
      - "currency"
      - "FX rates"
      - "trade war"
      - "tariffs"
      - "sanctions"
      - "supply chain"
      - "chip shortage"
      - "pandemic impact"
      - "COVID"
      - "stimulus"
      - "fiscal policy"
      - "government spending"
      - "deficit"
      - "debt ceiling"
      
    # Contextual indicators
    contextual:
      - "environment" # (market environment)
      - "conditions" # (economic conditions)
      - "backdrop"
      - "headwinds"
      - "tailwinds"
      - "uncertainty"
      - "outlook"
      - "forecast"
      - "expectations"
      - "sentiment"
      - "confidence"
      - "trends"
      - "cycle"
      - "normalized"
      - "disruption"
      - "pressure" # (market pressure)
  
  common_phrases:
    positive_signals:
      # Economic Strength
      - "strong economic growth"
      - "robust labor market"
      - "healthy consumer"
      - "economic expansion"
      - "soft landing scenario"
      - "inflation moderating"
      - "Fed pause likely"
      
      # Market Conditions
      - "favorable market conditions"
      - "improving credit spreads"
      - "strong equity markets"
      - "yield curve normalizing"
      - "market stability returning"
      
      # Industry
      - "competitive position strong"
      - "gaining market share"
      - "industry consolidation benefits"
      
    negative_signals:
      - "recession concerns"
      - "economic slowdown"
      - "elevated inflation"
      - "rising unemployment"
      - "market volatility"
      - "inverted yield curve"
      - "credit spreads widening"
      - "geopolitical tensions"
      - "competitive pressures"
      - "industry headwinds"
      - "uncertain environment"
  
  quantitative_patterns:
    # Economic metrics
    - "GDP growth of X%"
    - "inflation at X%"
    - "unemployment rate of X%"
    - "X rate hikes expected"
    
    # Market metrics
    - "S&P up/down X%"
    - "10-year yield at X%"
    - "credit spreads at X bps"
    - "VIX at X level"
    
    # Industry metrics
    - "industry growth of X%"
    - "market share of X%"
    - "X% of industry assets"
  
  bank_specific_terminology:
    # US Banks
    JPMorgan:
      commentary: ["Jamie Dimon's letter", "Economic outlook section"]
      focus: ["Global macro view", "Fortress balance sheet for any environment"]
      metrics: "Tracks 100+ economic variables"
      
    Bank_of_America:
      framework: ["Consumer checkpoint", "Economic scenarios"]
      data: "Real-time consumer spending data"
      
    Wells_Fargo:
      focus: ["US economic exposure", "Rate sensitivity"]
      
    Citigroup:
      perspective: ["Global economic view", "Emerging markets impact"]
      
    Goldman_Sachs:
      research: ["Global Investment Research", "Economic outlooks"]
      focus: "Market-dependent revenues"
      
    Morgan_Stanley:
      view: ["Wealth management resilience", "Market-linked revenues"]
    
    # Canadian Banks
    Royal_Bank_RY:
      focus: ["Canadian economic outlook", "US exposure"]
      factors: ["Housing market", "Commodity prices"]
      
    TD_Bank:
      exposure: ["North American economy", "Cross-border dynamics"]
      sensitivity: "Interest rate sensitive"
      
    Bank_of_Montreal_BMO:
      coverage: ["Canada-US corridor", "Economic integration"]
      
    Scotiabank_BNS:
      perspective: ["Pacific Alliance", "LatAm economies"]
      commodities: "Commodity price impacts"
      
    CIBC_CM:
      focus: ["Canadian-centric view", "Housing market focus"]
      
    National_Bank_NA:
      regional: ["Quebec economy", "Canadian focus"]
  
  canadian_specific_patterns:
    economic_factors:
      - Bank of Canada policy
      - CAD/USD exchange rate
      - Housing market (critical)
      - Commodity prices (oil, metals)
      - Resource sector health
      - US-Canada trade
      
    terminology:
      - "BoC" (Bank of Canada)
      - "Overnight rate"
      - "Canadian housing"
      - "Energy sector exposure"
      - "TSX performance"
      - "Provincial economies"
      
    sensitivities:
      - Higher rate sensitivity
      - Housing market dependency
      - Commodity price correlation
      - US economic spillover
      - Trade relationship impacts
  
  fed_policy_language:
    policy_tools:
      - "federal funds rate"
      - "discount rate"
      - "reserve requirements"
      - "open market operations"
      - "forward guidance"
      - "dot plot"
      
    policy_stance:
      - "accommodative"
      - "restrictive"
      - "neutral"
      - "data dependent"
      - "patient approach"
      - "gradual normalization"
      
    communication:
      - "FOMC minutes"
      - "Fed speak"
      - "Jackson Hole"
      - "Congressional testimony"
      - "press conferences"
  
  market_indicators:
    equity:
      - "market capitalization"
      - "P/E ratios"
      - "earnings expectations"
      - "sector rotation"
      - "risk on/risk off"
      
    credit:
      - "credit availability"
      - "lending standards"
      - "default rates"
      - "refinancing conditions"
      
    volatility:
      - "implied volatility"
      - "realized volatility"
      - "correlation changes"
      - "flight to quality"
  
  competitive_landscape:
    dynamics:
      - "market consolidation"
      - "new entrants"
      - "fintech disruption"
      - "big tech competition"
      - "nonbank lenders"
      
    factors:
      - "pricing power"
      - "customer acquisition costs"
      - "switching costs"
      - "network effects"
      - "scale advantages"
  
  geopolitical_factors:
    events:
      - "elections"
      - "trade agreements"
      - "military conflicts"
      - "sanctions regimes"
      - "regulatory changes"
      
    impacts:
      - "market volatility"
      - "capital flows"
      - "currency movements"
      - "commodity prices"
      - "supply chains"
  
  classification_examples:
    
    should_classify:
      - text: "The Fed's rate hiking cycle is nearing its end"
        reason: "Federal Reserve policy discussion"
        
      - text: "GDP growth slowed to 2% as expected"
        reason: "Macroeconomic indicator"
        
      - text: "Market volatility increased due to geopolitical tensions"
        reason: "Market conditions and geopolitical"
        
      - text: "Unemployment remains near historic lows at 3.5%"
        reason: "Labor market conditions"
        
      - text: "The yield curve inversion signals recession concerns"
        reason: "Market indicator and economic outlook"
        
      - text: "Competitive pressure intensifying from fintechs"
        reason: "Industry competitive dynamics"
        
      - text: "Housing market showing signs of cooling"
        reason: "Sector-specific economic indicator"
    
    should_not_classify:
      - text: "Our strategy focuses on organic growth"
        reason: "Company strategy, not macro"
        
      - text: "Credit losses remain below historical averages"
        reason: "Credit Quality category"
        
      - text: "We're investing in technology"
        reason: "Technology category"
        
      - text: "Revenue grew 10% this quarter"
        reason: "Company performance, not macro"
  
  co_occurrence_patterns:
    frequently_with:
      - "Net Interest Income" # Rate environment impact
      - "Credit Quality" # Economic impact on credit
      - "Business Strategy" # Macro drives strategy
      
    sometimes_with:
      - "Trading" # Market volatility impact
      - "Geographic" # Regional economics
      - "Capital Management" # Stress scenarios
      
    rarely_with:
      - "Technology" # Different focus
      - "Workforce" # Different domain
  
  economic_cycle_language:
    phases:
      - "expansion"
      - "peak"
      - "contraction"
      - "trough"
      - "recovery"
      - "late cycle"
      - "mid-cycle"
      - "early cycle"
      
    indicators:
      - "leading indicators"
      - "lagging indicators"
      - "coincident indicators"
      - "recession indicators"
      - "growth indicators"
  
  outlook_language:
    timeframes:
      - "near-term outlook"
      - "medium-term view"
      - "long-term perspective"
      - "through-the-cycle"
      
    scenarios:
      - "base case"
      - "upside scenario"
      - "downside risks"
      - "tail risks"
      - "black swan events"
  
  red_flags_for_misclassification:
    - "Company-specific strategy is not macro"
    - "Internal metrics are not market conditions"
    - "Product performance is business line category"
    - "Regulatory changes go to Regulatory category"
    - "Technology disruption may be Technology category"
    - "Bank's OWN credit quality is Credit category"
    - "Bank's OWN capital is Capital Management"

  prompt_guidance_for_llm: |
    When classifying content as Macro & Market Environment:
    
    CORE IDENTIFICATION:
    1. Look for EXTERNAL ECONOMIC and MARKET discussions
    2. Key themes: Economy, rates, inflation, markets, competition
    3. External factors affecting all banks
    4. Industry-wide trends and conditions
    5. Forward-looking economic commentary
    
    KEY COMPONENTS:
    6. Economic: GDP, inflation, unemployment, cycles
    7. Monetary: Fed/BoC policy, rates, QE/QT
    8. Markets: Equity, credit, volatility, yields
    9. Industry: Competition, consolidation, disruption
    10. Geopolitical: Trade, sanctions, political events
    
    ECONOMIC INDICATORS:
    - GDP growth rates
    - Inflation (CPI, PCE)
    - Unemployment rates
    - Consumer confidence
    - Business investment
    - Housing market
    - Wage growth
    
    MONETARY POLICY:
    US:
    - Federal Reserve/FOMC
    - Fed funds rate
    - Dot plot projections
    - QE/QT programs
    
    CANADA:
    - Bank of Canada
    - Overnight rate
    - Forward guidance
    - Currency impacts
    
    MARKET CONDITIONS:
    - Yield curve shape
    - Credit spreads
    - Equity valuations
    - Market volatility (VIX)
    - Liquidity conditions
    - IPO/M&A activity
    
    INDUSTRY DYNAMICS:
    - Market share shifts
    - Competitive pressures
    - Fintech disruption
    - Regulatory environment
    - Consolidation trends
    - Pricing dynamics
    
    GEOGRAPHIC DIFFERENCES:
    US FOCUS:
    - Fed policy dominance
    - Global market leader
    - Dollar strength
    - Diverse economy
    
    CANADIAN FOCUS:
    - Housing market critical
    - Commodity sensitivity
    - US spillover effects
    - Resource sector importance
    
    GEOPOLITICAL:
    - Trade relationships
    - Political stability
    - International conflicts
    - Sanctions regimes
    - Supply chain issues
    
    EXCLUSIONS:
    - Bank-specific strategies
    - Internal performance metrics
    - Company guidance
    - Product-specific discussions
    - Regulatory requirements (unless macro)
    
    REMEMBER:
    - This is about EXTERNAL environment
    - Affects entire industry
    - Sets context for performance
    - Forward-looking important
    - Distinguish from company-specific