# =====================================================
# Calendar Events Refresh Configuration
# =====================================================
# This configuration controls the calendar events ETL process
# that queries FactSet Calendar Events API and maintains a master
# CSV file with current earnings events data.

# SSL Certificate Configuration
ssl_cert_path: "Finance Data and Analytics/DSA/Earnings Call Transcripts/Inputs/Certificate/rbc-ca-bundle.cer"

# Calendar Refresh Configuration
calendar_refresh:
  description: "Query Calendar Events API and refresh master CSV"

  # Date Range Configuration
  # Controls how far back and forward to query for events
  date_range:
    past_months: 6      # Look back 6 months from today
    future_months: 6    # Look ahead 6 months from today
    # Note: Actual date calculation uses 30-day months as approximation

  # Event Types to Query
  # Currently only supporting Earnings events
  event_types:
    - "Earnings"

  # Output Paths (on NAS)
  master_database_path: "Finance Data and Analytics/DSA/Earnings Call Transcripts/Outputs/CalendarEvents/Database/master_calendar_events.csv"
  output_logs_path: "Finance Data and Analytics/DSA/Earnings Call Transcripts/Outputs/CalendarEvents/Logs"

  # Processing Configuration
  replace_on_refresh: true  # Always replace master CSV with fresh data (no incremental updates)

# =====================================================
# Monitored Institutions Configuration
# =====================================================
# Monitored institutions should be stored in a separate file:
# monitored_institutions.yaml (in the same directory as this config)
#
# The script will:
# 1. Try to load monitored_institutions.yaml from the same NAS directory
# 2. Fall back to this config file if monitored_institutions section exists here
#
# Format: ticker: {id, name, type, path_safe_name}
# Example:
#   RY-CA: {id: 1, name: "Royal Bank of Canada", type: "Canadian_Banks", ...}
#
# To use separate file (recommended):
# - Copy database_refresh/monitored_institutions.yaml to same NAS directory as this config
# - The script will automatically find and load it
#
# =====================================================
# Note: Monitored institutions are now in a separate file
# Copy monitored_institutions.yaml to the same NAS directory as this config.
# The script will automatically load it from there.
# =====================================================
