# Stage 0 Configuration
# Essential settings for historical transcript sync

# SSL Certificate Configuration
ssl_cert_path: "Inputs/certificate/certificate.cer"

# NAS Configuration (loaded from environment)
# nas_share_name comes from NAS_SHARE_NAME environment variable

# API Settings
api_settings:
  # Core API parameters
  industry_categories:
    - "IN:BANKS"
    - "IN:FNLSVC"
    - "IN:INS"
    - "IN:SECS"
  
  transcript_types:
    - "Corrected"
    - "Raw"
  
  # API request configuration
  sort_order:
    - "-storyDateTime"
  pagination_limit: 1000
  pagination_offset: 0
  
  # Rate limiting and retry settings
  request_delay: 3.0
  max_retries: 8
  retry_delay: 10.0
  use_exponential_backoff: true
  max_backoff_delay: 120.0

# Stage 0 specific settings
stage_0:
  description: "Historical download using 3-year rolling window"

# Monitored Financial Institutions
# Format: ticker: {name, type}
monitored_institutions:
  # Canadian Banks
  BMO-CA: {name: "Bank of Montreal", type: "Canadian"}
  CM-CA: {name: "Canadian Imperial Bank of Commerce", type: "Canadian"}
  NA-CA: {name: "National Bank of Canada", type: "Canadian"}
  RY-CA: {name: "Royal Bank of Canada", type: "Canadian"}
  BNS-CA: {name: "Bank of Nova Scotia", type: "Canadian"}
  TD-CA: {name: "Toronto-Dominion Bank", type: "Canadian"}
  
  # European Banks
  BBVA-ES: {name: "Banco Bilbao Vizcaya Argentaria S.A.", type: "European"}
  BCS-GB: {name: "Barclays PLC", type: "European"}
  BNP-FR: {name: "BNP Paribas", type: "European"}
  DBK-DE: {name: "Deutsche Bank AG", type: "European"}
  HSBA-GB: {name: "HSBC Holdings plc", type: "European"}
  ING-NL: {name: "ING Groep N.V.", type: "European"}
  ISP-IT: {name: "Intesa Sanpaolo", type: "European"}
  LLOY-GB: {name: "Lloyds Banking Group plc", type: "European"}
  RBS-GB: {name: "NatWest Group plc", type: "European"}
  SAN-ES: {name: "Banco Santander S.A.", type: "European"}
  GLE-FR: {name: "Societe Generale", type: "European"}
  STAN-GB: {name: "Standard Chartered PLC", type: "European"}
  UBS-CH: {name: "UBS Group AG", type: "European"}
  UCG-IT: {name: "UniCredit S.p.A.", type: "European"}
  
  # Insurance Companies
  GWO-CA: {name: "Great-West Lifeco Inc.", type: "Insurance"}
  IFC-CA: {name: "Intact Financial Corporation", type: "Insurance"}
  MFC-CA: {name: "Manulife Financial Corporation", type: "Insurance"}
  SLF-CA: {name: "Sun Life Financial Inc.", type: "Insurance"}
  
  # U.S. Banks
  BAC-US: {name: "Bank of America Corporation", type: "US"}
  C-US: {name: "Citigroup Inc.", type: "US"}
  GS-US: {name: "Goldman Sachs Group Inc.", type: "US"}
  JPM-US: {name: "JPMorgan Chase & Co.", type: "US"}
  MS-US: {name: "Morgan Stanley", type: "US"}
  WFC-US: {name: "Wells Fargo & Company", type: "US"}
  
  # U.S. Boutiques
  CCO-CA: {name: "Canaccord Genuity Group Inc", type: "US_Boutique"}
  EVR-US: {name: "Evercore Inc", type: "US_Boutique"}
  HLI-US: {name: "Houlihan Lokey Inc", type: "US_Boutique"}
  LAZ-US: {name: "Lazard Ltd", type: "US_Boutique"}
  MC-US: {name: "Moelis & Company", type: "US_Boutique"}
  PIPR-US: {name: "Piper Sandler Companies", type: "US_Boutique"}
  PJT-US: {name: "PJT Partners Inc", type: "US_Boutique"}
  RJF-US: {name: "Raymond James Financial Inc", type: "US_Boutique"}
  SF-US: {name: "Stifel Financial Corp", type: "US_Boutique"}