# Stage 0 Configuration
# Essential settings for historical transcript sync

# SSL Certificate Configuration
ssl_cert_path: "Finance Data and Analytics/DSA/Earnings Call Transcripts/Inputs/Certificate/rbc-ca-bundle.cer"

# NAS Configuration (loaded from environment)
# nas_share_name comes from NAS_SHARE_NAME environment variable

# API Settings
api_settings:
  # Core API parameters
  industry_categories:
    - "IN:BANKS"
    - "IN:FNLSVC"
    - "IN:INS"
    - "IN:SECS"
  
  transcript_types:
    - "Corrected"
    - "Raw"
  
  # API request configuration
  sort_order:
    - "-storyDateTime"
  pagination_limit: 1000
  pagination_offset: 0
  
  # Rate limiting and retry settings
  request_delay: 3.0
  max_retries: 8
  retry_delay: 10.0
  use_exponential_backoff: true
  max_backoff_delay: 120.0

# Stage 00 specific settings
stage_00_download_historical:
  description: "Historical download using 3-year rolling window"
  output_data_path: "Finance Data and Analytics/DSA/Earnings Call Transcripts/Outputs/Data"
  output_logs_path: "Finance Data and Analytics/DSA/Earnings Call Transcripts/Outputs/Logs"

# Stage 01 specific settings
stage_01_download_daily:
  description: "Daily incremental sync of recent transcripts"
  sync_date_range: 1  # Number of days to look back (0 = today only, 1 = today + yesterday)
  output_data_path: "Finance Data and Analytics/DSA/Earnings Call Transcripts/Outputs/Data"
  output_logs_path: "Finance Data and Analytics/DSA/Earnings Call Transcripts/Outputs/Logs"

# Stage 02 specific settings
stage_02_database_sync:
  description: "Transcript consolidation and master database management"
  input_data_path: "Finance Data and Analytics/DSA/Earnings Call Transcripts/Outputs/Data"
  output_logs_path: "Finance Data and Analytics/DSA/Earnings Call Transcripts/Outputs/Logs"
  master_database_path: "Finance Data and Analytics/DSA/Earnings Call Transcripts/Outputs/Database/master_database.json"
  refresh_output_path: "Finance Data and Analytics/DSA/Earnings Call Transcripts/Outputs/Refresh"

# Stage 03 specific settings
stage_03_extract_content:
  description: "XML content extraction and paragraph-level breakdown"
  input_queue_path: "Finance Data and Analytics/DSA/Earnings Call Transcripts/Outputs/Refresh/stage_02_process_queue.json"
  output_logs_path: "Finance Data and Analytics/DSA/Earnings Call Transcripts/Outputs/Logs"
  output_data_path: "Finance Data and Analytics/DSA/Earnings Call Transcripts/Outputs/Refresh"
  dev_mode: true
  dev_max_files: 2

# Stage 04 specific settings
stage_04_validate_structure:
  description: "Transcript content validation"
  input_data_path: "Finance Data and Analytics/DSA/Earnings Call Transcripts/Outputs/Refresh/stage_03_extracted_content.json"
  output_logs_path: "Finance Data and Analytics/DSA/Earnings Call Transcripts/Outputs/Logs"
  output_data_path: "Finance Data and Analytics/DSA/Earnings Call Transcripts/Outputs/Refresh"
  dev_mode: true
  dev_max_files: 2
  expected_sections:
    - "MANAGEMENT DISCUSSION SECTION"
    - "Q&A"

# Stage 05 specific settings (Sliding Window Q&A Pairing)
stage_05_qa_pairing:
  description: "Sliding window Q&A boundary detection and analyst session pairing"
  input_data_path: "Finance Data and Analytics/DSA/Earnings Call Transcripts/Outputs/Refresh/stage_04_validated_content.json"
  output_data_path: "Finance Data and Analytics/DSA/Earnings Call Transcripts/Outputs/Refresh"
  output_logs_path: "Finance Data and Analytics/DSA/Earnings Call Transcripts/Outputs/Logs"
  dev_mode: true
  dev_max_transcripts: 2
  window_size: 5  # Number of speaker blocks per sliding window
  
  # LLM Configuration (OAuth client credentials come from environment variables)
  llm_config:
    base_url: "https://api.openai.com/v1"
    model: "gpt-4o-mini"
    temperature: 0.1
    max_tokens: 500  # Increased for more complex sliding window prompts
    timeout: 60
    max_retries: 3
    token_endpoint: "https://auth.example.com/oauth/token"  # Replace with actual OAuth endpoint
    cost_per_1k_prompt_tokens: 0.00015
    cost_per_1k_completion_tokens: 0.0006

# Stage 06 specific settings (LLM Financial Classification)
stage_06_llm_classification:
  description: "LLM-based financial content classification"
  input_data_path: "Finance Data and Analytics/DSA/Earnings Call Transcripts/Outputs/Refresh/stage_05_qa_paired_content.json"
  output_data_path: "Finance Data and Analytics/DSA/Earnings Call Transcripts/Outputs/Refresh"
  output_logs_path: "Finance Data and Analytics/DSA/Earnings Call Transcripts/Outputs/Logs"
  dev_mode: true
  dev_max_transcripts: 2
  
  # Processing configuration
  processing_config:
    md_paragraph_window_size: 5          # Paragraphs per MD classification call
    max_speaker_blocks_context: 2        # Prior speaker blocks for context
    prior_block_preview_chars: 750       # Characters to show from prior blocks
  
  # LLM configuration
  llm_config:
    base_url: "https://api.openai.com/v1"
    model: "gpt-4o-2024-08-06"
    temperature: 0.0
    max_tokens: 500
    cost_per_1k_prompt_tokens: 0.0025
    cost_per_1k_completion_tokens: 0.01
    timeout: 30
    max_retries: 3
    token_endpoint: "https://auth.example.com/oauth/token"  # Replace with actual OAuth endpoint
  
  # Financial categories for classification
  financial_categories:
    - name: "Revenue & Growth"
      description: "Discussions about revenue performance, growth rates, sales trends, and top-line metrics"
      key_indicators: "revenue, sales, growth, top-line, organic growth, acquisition growth"
      use_when: "Content discusses revenue figures, growth percentages, sales performance, or revenue drivers"
      example_phrases: "revenue grew by, sales increased, top-line performance, organic growth of"
    
    - name: "Profitability & Margins"
      description: "Content about profit margins, profitability metrics, margin expansion or compression"
      key_indicators: "margin, profit, profitability, efficiency ratio, return on equity, return on assets"
      use_when: "Discussion of profit margins, cost efficiency, or profitability metrics"
      example_phrases: "net interest margin, efficiency ratio, return on equity, margin expansion"
    
    - name: "Credit & Risk Management"
      description: "Credit quality, loan loss provisions, risk management practices, and credit metrics"
      key_indicators: "credit loss, provision, impairment, allowance, risk management, credit quality"
      use_when: "Discussion of credit provisions, loan quality, or risk management practices"
      example_phrases: "provision for credit losses, impaired loans, credit quality, risk management"
    
    - name: "Capital Management"
      description: "Capital ratios, capital adequacy, capital allocation, and regulatory capital"
      key_indicators: "capital ratio, tier 1, common equity, capital adequacy, capital allocation"
      use_when: "Discussion of capital strength, regulatory ratios, or capital deployment"
      example_phrases: "CET1 ratio, tier 1 capital, capital adequacy, capital allocation"
    
    - name: "Business Strategy & Outlook"
      description: "Strategic initiatives, business outlook, guidance, and long-term plans"
      key_indicators: "strategy, outlook, guidance, initiative, transformation, digital"
      use_when: "Discussion of future plans, strategic direction, or business transformation"
      example_phrases: "our strategy, looking forward, digital transformation, strategic initiative"
    
    - name: "Market Conditions & Environment"
      description: "Economic environment, market conditions, regulatory changes, and external factors"
      key_indicators: "market, environment, economic, regulatory, interest rate, competition"
      use_when: "Discussion of external factors affecting the business"
      example_phrases: "market conditions, economic environment, regulatory changes, competitive landscape"
    
    - name: "Operations & Efficiency"
      description: "Operational performance, cost management, efficiency initiatives, and productivity"
      key_indicators: "operations, efficiency, cost, productivity, automation, digitization"
      use_when: "Discussion of operational improvements, cost reduction, or efficiency gains"
      example_phrases: "operational efficiency, cost reduction, productivity gains, automation"
    
    - name: "Geographic Performance"
      description: "Performance by geographic region, international operations, and regional trends"
      key_indicators: "geographic, region, international, domestic, Canada, US, Europe"
      use_when: "Discussion of performance by region or geographic segment"
      example_phrases: "in Canada, US operations, international business, regional performance"
    
    - name: "Product & Services"
      description: "Specific products, services, business lines, and segment performance"
      key_indicators: "product, service, business line, segment, wealth management, commercial banking"
      use_when: "Discussion of specific business segments, products, or services"
      example_phrases: "wealth management, commercial banking, personal banking, capital markets"
    
    - name: "Digital & Technology"
      description: "Technology investments, digital capabilities, innovation, and tech-related initiatives"
      key_indicators: "digital, technology, innovation, platform, mobile, online, fintech"
      use_when: "Discussion of technology investments, digital transformation, or innovation"
      example_phrases: "digital platform, technology investment, mobile banking, innovation"
    
    - name: "Regulatory & Compliance"
      description: "Regulatory requirements, compliance matters, and regulatory capital"
      key_indicators: "regulatory, compliance, regulation, Basel, IFRS, stress test"
      use_when: "Discussion of regulatory matters, compliance, or regulatory capital"
      example_phrases: "regulatory requirements, Basel III, stress testing, compliance"
    
    - name: "ESG & Sustainability"
      description: "Environmental, social, and governance matters, sustainability initiatives"
      key_indicators: "ESG, sustainability, climate, environment, governance, social"
      use_when: "Discussion of ESG factors, sustainability, or corporate responsibility"
      example_phrases: "climate risk, sustainability, ESG, environmental, governance"
    
    - name: "Other"
      description: "Content that doesn't fit other categories, introductions, procedural matters"
      use_when: "Non-financial content, introductions, procedural matters, or unclear topics"
      example_phrases: "thank you, good morning, operator, next question"

# Database Configuration (for stages that use PostgreSQL)
database:
  host: localhost
  port: 5432
  name: factset_transcripts
  user: postgres
  password: postgres  # Update with your actual password

# Stage 08 specific settings (Embeddings Generation)
stage_08_embeddings_generation:
  description: "Generate embeddings from summarized content"
  
  # LLM configuration (uses same OAuth as Stage 07)
  llm_config:
    base_url: "https://api.openai.com/v1"
    model: "text-embedding-3-large"
    timeout: 30
    max_retries: 3
    token_endpoint: "https://auth.example.com/oauth/token"  # Same as Stage 07

# Stage 07 specific settings (LLM Content Summarization)
stage_07_llm_summarization:
  description: "LLM-based content summarization"
  input_data_path: "Finance Data and Analytics/DSA/Earnings Call Transcripts/Outputs/Refresh/stage_06_classified_content.json"
  output_data_path: "Finance Data and Analytics/DSA/Earnings Call Transcripts/Outputs/Refresh"
  output_logs_path: "Finance Data and Analytics/DSA/Earnings Call Transcripts/Outputs/Logs"
  dev_mode: true
  dev_max_transcripts: 2
  
  # LLM configuration
  llm_config:
    base_url: "https://api.openai.com/v1"
    model: "gpt-4o-2024-08-06"
    temperature: 0.1
    max_tokens: 1000
    cost_per_1k_prompt_tokens: 0.0025
    cost_per_1k_completion_tokens: 0.01
    timeout: 30
    token_endpoint: "https://auth.example.com/oauth/token"  # Replace with actual OAuth endpoint


# Monitored Financial Institutions
# Format: ticker: {name, type}
monitored_institutions:
  # Canadian Banks
  BMO-CA: {name: "Bank of Montreal", type: "Canadian", path_safe_name: "BMO-CA_Bank_of_Montreal"}
  CM-CA: {name: "Canadian Imperial Bank of Commerce", type: "Canadian", path_safe_name: "CM-CA_Canadian_Imperial_Bank_of_Commerce"}
  NA-CA: {name: "National Bank of Canada", type: "Canadian", path_safe_name: "NA-CA_National_Bank_of_Canada"}
  RY-CA: {name: "Royal Bank of Canada", type: "Canadian", path_safe_name: "RY-CA_Royal_Bank_of_Canada"}
  BNS-CA: {name: "Bank of Nova Scotia", type: "Canadian", path_safe_name: "BNS-CA_Bank_of_Nova_Scotia"}
  TD-CA: {name: "Toronto-Dominion Bank", type: "Canadian", path_safe_name: "TD-CA_Toronto-Dominion_Bank"}
  
  # European Banks
  BBVA-ES: {name: "Banco Bilbao Vizcaya Argentaria S.A.", type: "European", path_safe_name: "BBVA-ES_Banco_Bilbao_Vizcaya_Argentaria_SA"}
  BCS-GB: {name: "Barclays PLC", type: "European", path_safe_name: "BCS-GB_Barclays_PLC"}
  BNP-FR: {name: "BNP Paribas", type: "European", path_safe_name: "BNP-FR_BNP_Paribas"}
  DBK-DE: {name: "Deutsche Bank AG", type: "European", path_safe_name: "DBK-DE_Deutsche_Bank_AG"}
  HSBA-GB: {name: "HSBC Holdings plc", type: "European", path_safe_name: "HSBA-GB_HSBC_Holdings_plc"}
  ING-NL: {name: "ING Groep N.V.", type: "European", path_safe_name: "ING-NL_ING_Groep_NV"}
  ISP-IT: {name: "Intesa Sanpaolo", type: "European", path_safe_name: "ISP-IT_Intesa_Sanpaolo"}
  LLOY-GB: {name: "Lloyds Banking Group plc", type: "European", path_safe_name: "LLOY-GB_Lloyds_Banking_Group_plc"}
  RBS-GB: {name: "NatWest Group plc", type: "European", path_safe_name: "RBS-GB_NatWest_Group_plc"}
  SAN-ES: {name: "Banco Santander S.A.", type: "European", path_safe_name: "SAN-ES_Banco_Santander_SA"}
  GLE-FR: {name: "Societe Generale", type: "European", path_safe_name: "GLE-FR_Societe_Generale"}
  STAN-GB: {name: "Standard Chartered PLC", type: "European", path_safe_name: "STAN-GB_Standard_Chartered_PLC"}
  UBS-CH: {name: "UBS Group AG", type: "European", path_safe_name: "UBS-CH_UBS_Group_AG"}
  UCG-IT: {name: "UniCredit S.p.A.", type: "European", path_safe_name: "UCG-IT_UniCredit_SpA"}
  
  # Insurance Companies
  GWO-CA: {name: "Great-West Lifeco Inc.", type: "Insurance", path_safe_name: "GWO-CA_Great-West_Lifeco_Inc"}
  IFC-CA: {name: "Intact Financial Corporation", type: "Insurance", path_safe_name: "IFC-CA_Intact_Financial_Corporation"}
  MFC-CA: {name: "Manulife Financial Corporation", type: "Insurance", path_safe_name: "MFC-CA_Manulife_Financial_Corporation"}
  SLF-CA: {name: "Sun Life Financial Inc.", type: "Insurance", path_safe_name: "SLF-CA_Sun_Life_Financial_Inc"}
  
  # U.S. Banks
  BAC-US: {name: "Bank of America Corporation", type: "US", path_safe_name: "BAC-US_Bank_of_America_Corporation"}
  C-US: {name: "Citigroup Inc.", type: "US", path_safe_name: "C-US_Citigroup_Inc"}
  GS-US: {name: "Goldman Sachs Group Inc.", type: "US", path_safe_name: "GS-US_Goldman_Sachs_Group_Inc"}
  JPM-US: {name: "JPMorgan Chase & Co.", type: "US", path_safe_name: "JPM-US_JPMorgan_Chase_Co"}
  MS-US: {name: "Morgan Stanley", type: "US", path_safe_name: "MS-US_Morgan_Stanley"}
  WFC-US: {name: "Wells Fargo & Company", type: "US", path_safe_name: "WFC-US_Wells_Fargo_Company"}
  
  # U.S. Boutiques
  CCO-CA: {name: "Canaccord Genuity Group Inc", type: "US_Boutique", path_safe_name: "CCO-CA_Canaccord_Genuity_Group_Inc"}
  EVR-US: {name: "Evercore Inc", type: "US_Boutique", path_safe_name: "EVR-US_Evercore_Inc"}
  HLI-US: {name: "Houlihan Lokey Inc", type: "US_Boutique", path_safe_name: "HLI-US_Houlihan_Lokey_Inc"}
  LAZ-US: {name: "Lazard Ltd", type: "US_Boutique", path_safe_name: "LAZ-US_Lazard_Ltd"}
  MC-US: {name: "Moelis & Company", type: "US_Boutique", path_safe_name: "MC-US_Moelis_Company"}
  PIPR-US: {name: "Piper Sandler Companies", type: "US_Boutique", path_safe_name: "PIPR-US_Piper_Sandler_Companies"}
  PJT-US: {name: "PJT Partners Inc", type: "US_Boutique", path_safe_name: "PJT-US_PJT_Partners_Inc"}
  RJF-US: {name: "Raymond James Financial Inc", type: "US_Boutique", path_safe_name: "RJF-US_Raymond_James_Financial_Inc"}
  SF-US: {name: "Stifel Financial Corp", type: "US_Boutique", path_safe_name: "SF-US_Stifel_Financial_Corp"}